name: Sync Fork

on:
  schedule:
    - cron: '0 6 * * *'  # 매일 오전 6시 (UTC)
  workflow_dispatch:      # 수동 실행도 허용

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/joshhighet/ransomwatch.git
          git fetch upstream

      - name: Merge upstream/main into main
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories --no-edit || true

      - name: Push changes
        run: |
          git push origin main
